// Top 100 HSK 1–2 words for HSK badge lookups; the first 25 are the starter deck.
// Format: [hanzi, pinyin (tone marks), English definition]
export type HskWord = { hanzi: string; pinyin: string; definition: string; level: 1 | 2 };

export const HSK_100: HskWord[] = [
  // HSK 1 (most basic)
  { hanzi: "你好", pinyin: "nǐ hǎo", definition: "hello", level: 1 },
  { hanzi: "谢谢", pinyin: "xiè xiè", definition: "thank you", level: 1 },
  { hanzi: "再见", pinyin: "zài jiàn", definition: "goodbye", level: 1 },
  { hanzi: "我", pinyin: "wǒ", definition: "I, me", level: 1 },
  { hanzi: "你", pinyin: "nǐ", definition: "you", level: 1 },
  { hanzi: "他", pinyin: "tā", definition: "he, him", level: 1 },
  { hanzi: "她", pinyin: "tā", definition: "she, her", level: 1 },
  { hanzi: "们", pinyin: "men", definition: "plural marker", level: 1 },
  { hanzi: "的", pinyin: "de", definition: "structural particle (of)", level: 1 },
  { hanzi: "是", pinyin: "shì", definition: "to be", level: 1 },
  { hanzi: "不", pinyin: "bù", definition: "not, no", level: 1 },
  { hanzi: "有", pinyin: "yǒu", definition: "to have", level: 1 },
  { hanzi: "在", pinyin: "zài", definition: "to be at, in, on", level: 1 },
  { hanzi: "这", pinyin: "zhè", definition: "this", level: 1 },
  { hanzi: "那", pinyin: "nà", definition: "that", level: 1 },
  { hanzi: "什么", pinyin: "shén me", definition: "what", level: 1 },
  { hanzi: "哪", pinyin: "nǎ", definition: "which", level: 1 },
  { hanzi: "好", pinyin: "hǎo", definition: "good, well", level: 1 },
  { hanzi: "大", pinyin: "dà", definition: "big, large", level: 1 },
  { hanzi: "小", pinyin: "xiǎo", definition: "small, little", level: 1 },
  { hanzi: "多", pinyin: "duō", definition: "many, much", level: 1 },
  { hanzi: "少", pinyin: "shǎo", definition: "few, little", level: 1 },
  { hanzi: "几", pinyin: "jǐ", definition: "how many, several", level: 1 },
  { hanzi: "一", pinyin: "yī", definition: "one", level: 1 },
  { hanzi: "二", pinyin: "èr", definition: "two", level: 1 },
  { hanzi: "三", pinyin: "sān", definition: "three", level: 1 },
  { hanzi: "四", pinyin: "sì", definition: "four", level: 1 },
  { hanzi: "五", pinyin: "wǔ", definition: "five", level: 1 },
  { hanzi: "六", pinyin: "liù", definition: "six", level: 1 },
  { hanzi: "七", pinyin: "qī", definition: "seven", level: 1 },
  { hanzi: "八", pinyin: "bā", definition: "eight", level: 1 },
  { hanzi: "九", pinyin: "jiǔ", definition: "nine", level: 1 },
  { hanzi: "十", pinyin: "shí", definition: "ten", level: 1 },
  { hanzi: "百", pinyin: "bǎi", definition: "hundred", level: 1 },
  { hanzi: "中国", pinyin: "zhōng guó", definition: "China", level: 1 },
  { hanzi: "人", pinyin: "rén", definition: "person, people", level: 1 },
  { hanzi: "学生", pinyin: "xué shēng", definition: "student", level: 1 },
  { hanzi: "老师", pinyin: "lǎo shī", definition: "teacher", level: 1 },
  { hanzi: "朋友", pinyin: "péng yǒu", definition: "friend", level: 1 },
  { hanzi: "爸爸", pinyin: "bà ba", definition: "dad, father", level: 1 },
  { hanzi: "妈妈", pinyin: "mā ma", definition: "mum, mother", level: 1 },
  { hanzi: "名字", pinyin: "míng zì", definition: "name", level: 1 },
  { hanzi: "今天", pinyin: "jīn tiān", definition: "today", level: 1 },
  { hanzi: "明天", pinyin: "míng tiān", definition: "tomorrow", level: 1 },
  { hanzi: "年", pinyin: "nián", definition: "year", level: 1 },
  { hanzi: "月", pinyin: "yuè", definition: "month", level: 1 },
  { hanzi: "号", pinyin: "hào", definition: "date (of month), number", level: 1 },
  { hanzi: "上", pinyin: "shàng", definition: "on, above, upper", level: 1 },
  { hanzi: "下", pinyin: "xià", definition: "under, below, next", level: 1 },
  { hanzi: "去", pinyin: "qù", definition: "to go", level: 1 },
  { hanzi: "来", pinyin: "lái", definition: "to come", level: 1 },
  { hanzi: "吃", pinyin: "chī", definition: "to eat", level: 1 },
  { hanzi: "喝", pinyin: "hē", definition: "to drink", level: 1 },
  { hanzi: "说", pinyin: "shuō", definition: "to speak, to say", level: 1 },
  { hanzi: "看", pinyin: "kàn", definition: "to look, to see, to read", level: 1 },
  { hanzi: "听", pinyin: "tīng", definition: "to listen, to hear", level: 1 },
  { hanzi: "写", pinyin: "xiě", definition: "to write", level: 1 },
  { hanzi: "读", pinyin: "dú", definition: "to read aloud", level: 1 },
  { hanzi: "学", pinyin: "xué", definition: "to study, to learn", level: 1 },
  { hanzi: "爱", pinyin: "ài", definition: "to love", level: 1 },
  { hanzi: "要", pinyin: "yào", definition: "to want, will", level: 1 },
  { hanzi: "可以", pinyin: "kě yǐ", definition: "can, may", level: 1 },
  { hanzi: "不客气", pinyin: "bù kè qi", definition: "you're welcome", level: 1 },
  { hanzi: "对不起", pinyin: "duì bu qǐ", definition: "sorry, I apologize", level: 1 },
  { hanzi: "没关系", pinyin: "méi guān xi", definition: "never mind, it's OK", level: 1 },
  { hanzi: "请问", pinyin: "qǐng wèn", definition: "excuse me (may I ask)", level: 1 },
  // HSK 2
  { hanzi: "但是", pinyin: "dàn shì", definition: "but, however", level: 2 },
  { hanzi: "所以", pinyin: "suǒ yǐ", definition: "so, therefore", level: 2 },
  { hanzi: "因为", pinyin: "yīn wèi", definition: "because", level: 2 },
  { hanzi: "如果", pinyin: "rú guǒ", definition: "if, in case", level: 2 },
  { hanzi: "虽然", pinyin: "suī rán", definition: "although, even though", level: 2 },
  { hanzi: "已经", pinyin: "yǐ jīng", definition: "already", level: 2 },
  { hanzi: "还", pinyin: "hái", definition: "still, yet, also", level: 2 },
  { hanzi: "都", pinyin: "dōu", definition: "all, both", level: 2 },
  { hanzi: "很", pinyin: "hěn", definition: "very, quite", level: 2 },
  { hanzi: "太", pinyin: "tài", definition: "too (excessively)", level: 2 },
  { hanzi: "非常", pinyin: "fēi cháng", definition: "very, extremely", level: 2 },
  { hanzi: "一起", pinyin: "yī qǐ", definition: "together", level: 2 },
  { hanzi: "知道", pinyin: "zhī dào", definition: "to know", level: 2 },
  { hanzi: "觉得", pinyin: "jué de", definition: "to feel, to think", level: 2 },
  { hanzi: "希望", pinyin: "xī wàng", definition: "to hope, hope", level: 2 },
  { hanzi: "认为", pinyin: "rèn wéi", definition: "to think, to believe", level: 2 },
  { hanzi: "喜欢", pinyin: "xǐ huān", definition: "to like, to enjoy", level: 2 },
  { hanzi: "帮助", pinyin: "bāng zhù", definition: "to help, help", level: 2 },
  { hanzi: "告诉", pinyin: "gào sù", definition: "to tell, to inform", level: 2 },
  { hanzi: "回", pinyin: "huí", definition: "to return, to reply", level: 2 },
  { hanzi: "开始", pinyin: "kāi shǐ", definition: "to start, beginning", level: 2 },
  { hanzi: "完成", pinyin: "wán chéng", definition: "to complete, to finish", level: 2 },
  { hanzi: "问题", pinyin: "wèn tí", definition: "problem, question", level: 2 },
  { hanzi: "时间", pinyin: "shí jiān", definition: "time", level: 2 },
  { hanzi: "地方", pinyin: "dì fāng", definition: "place, location", level: 2 },
  { hanzi: "工作", pinyin: "gōng zuò", definition: "work, job; to work", level: 2 },
  { hanzi: "身体", pinyin: "shēn tǐ", definition: "body, health", level: 2 },
  { hanzi: "天气", pinyin: "tiān qì", definition: "weather", level: 2 },
  { hanzi: "汉语", pinyin: "hàn yǔ", definition: "Chinese (Mandarin)", level: 2 },
  { hanzi: "努力", pinyin: "nǔ lì", definition: "to work hard, diligent", level: 2 },
  { hanzi: "高兴", pinyin: "gāo xìng", definition: "happy, glad", level: 2 },
  { hanzi: "快乐", pinyin: "kuài lè", definition: "happy, joyful", level: 2 },
  { hanzi: "漂亮", pinyin: "piào liàng", definition: "beautiful, pretty", level: 2 },
  { hanzi: "方便", pinyin: "fāng biàn", definition: "convenient", level: 2 },
  { hanzi: "重要", pinyin: "zhòng yào", definition: "important", level: 2 },
];

export const AI_SENTENCE_MAX_WORDS = 50;
export const STARTER_DECK_SIZE = 25;
export const HSK_STARTER = HSK_100.slice(0, STARTER_DECK_SIZE);

const _lookup = new Map(HSK_100.map((w) => [w.hanzi, w]));

/** Return the HSK entry for a word (exact match), or null. */
export function hskLookup(hanzi: string): HskWord | null {
  return _lookup.get(hanzi) ?? null;
}
